### ISSUE TITLE
Pinyin needs an apostrophe sometimes

### ISSUE THREAD

**Issue by webmagnets** [peterolson/hanzi-tools#4]
Here is a link that states the rule: http://www.pinyin.info/romanization/hanyu/apostrophes.html

Here is a quote:

> Put an apostrophe before any syllable that begins with a, e, or o, unless that syllable comes at the beginning of a word or immediately follows a hyphen or other dash.

p.s. You've made a great tool. I can add the apostrophe client side when needed.

**Comment by peterolson** [comment]
Should be fixed now. Thanks!
