### ISSUE TITLE
What's wrong with the B

### ISSUE THREAD

**Issue by bastianspirek** [peterolson/hanzi-tools#6]
I was trying to pinyinify the phrase "我叫Bastian“ and noticed that the B will become bī, although it is obviously not a chinese character. Is this a bug or is there something I don't know about? It is the only letter that has this problem.
![image](https://user-images.githubusercontent.com/7038550/73593763-dc388280-4507-11ea-94d5-0fc91ed8e107.png)

**Comment by peterolson** [comment]
Good catch, this is caused because the letter "B" is an entry in the CC-CEDICT dictionary:

`B B [bi1] /euphemistic variant of 屄[bi1]/`

I have removed this entry from the dictionary. This should fix the issue.
